steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "--target", "test", "-t", "secret-backup-operator-test", "."]
  - name: "secret-backup-operator-test"
    dir: "/usr/secret-backup-operator"
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "eu.gcr.io/ems-gap-images/secret-backup-operator:$TAG_NAME",
        ".",
      ]
images: ["eu.gcr.io/ems-gap-images/secret-backup-operator:$TAG_NAME"]
tags: ["secret-backup-operator"]
