steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "--target", "test", "-t", "secret-backup-operator-test", "."]
  - name: "secret-backup-operator-test"
    dir: "/usr/secret-backup-operator"
tags: ["secret-backup-operator"]
